# Generated by Django 5.0.7 on 2024-09-09 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('group', models.CharField(blank=True, choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('allied-health', 'Allied Health'), ('support', 'Support'), ('management', 'Management'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('work_status', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('consultant', 'Consultant'), ('temporary', 'Temporary')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('assigned_treatment', models.TextField(blank=True)),
                ('working_days', models.JSONField()),
                ('available', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('medical', 'Medical'), ('nursing', 'Nursing'), ('allied-health', 'Allied Health'), ('support', 'Support'), ('management', 'Management'), ('administrative', 'Administrative'), ('other', 'Other')], default='patient', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='useraccount_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='useraccount_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, db_column='dateofbirth', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_column='gender', max_length=6)),
                ('contact_number', models.CharField(db_column='contactnumber', max_length=20, unique=True)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('work', models.CharField(blank=True, db_column='work', max_length=45, null=True)),
                ('height', models.FloatField(db_column='height')),
                ('ssn', models.CharField(blank=True, db_column='ssn', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('discharged', 'Discharged'), ('observation', 'Observation')], db_column='status', default='active', max_length=25)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
