# Generated by Django 5.0.7 on 2024-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medical', 'Medical'), ('nursing', 'Nursing'), ('allied-health', 'Allied Health'), ('support', 'Support'), ('management', 'Management'), ('administrative', 'Administrative'), ('other', 'Other')], default='patient', max_length=50),
        ),
    ]
