# Generated by Django 5.0.7 on 2024-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20),
        ),
    ]
