# Generated by Django 5.0.7 on 2024-08-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
