# Generated by Django 5.0.7 on 2024-07-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
    ]
