# Generated by Django 5.0.7 on 2024-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_available'),
        ('clinic', '0004_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='appointments',
            field=models.ManyToManyField(related_name='doctors', to='clinic.appointment'),
        ),
    ]
