# Generated by Django 5.0.7 on 2024-08-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-14'),
            preserve_default=False,
        ),
    ]
