# Generated by Django 5.0.7 on 2024-09-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='treatment_name', max_length=200)),
                ('price', models.IntegerField(db_column='price')),
                ('estimated_duration', models.TextField(db_column='estimated_duration')),
                ('visit_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], db_column='visit_type', max_length=20)),
            ],
            options={
                'db_table': 'treatmentss',
                'managed': True,
            },
        ),
    ]
