# Generated by Django 5.0.7 on 2024-09-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_treatment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treatment',
            table='treatments',
        ),
    ]
