# Generated by Django 5.0.7 on 2024-09-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_appointments'),
        ('clinic', '0004_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.patient'),
        ),
    ]
